services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx:/etc/nginx
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - webnet

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump

  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    volumes: 
      - ./auth_service:/app
    ports:
      - "5001:5000"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
